project_name: openfga-language

builds:
  -
    main: ./main.go
    binary: openfga-parser
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-s -w"
      - "-X github.com/openfga/language/internal/build.Version=v{{ .Version }}"
      - "-X github.com/openfga/language/internal/build.Commit={{.Commit}}"
      - "-X github.com/openfga/language/internal/build.Date={{.Date}}"

dockers:
  - goos: linux
    goarch: amd64

    dockerfile: Dockerfile

    image_templates:
      - "openfga/language:latest-amd64"
      - "openfga/language:{{ .Tag }}-amd64"
      - "openfga/language:v{{ .Version }}-amd64"
      - "openfga/language:v{{ .Major }}-amd64"
      - "openfga/language:v{{ .Major }}.{{ .Minor }}-amd64"
      - "openfga/language:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"

    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"

  - goos: linux
    goarch: arm64

    dockerfile: Dockerfile

    image_templates:
      - "openfga/language:latest-arm64"
      - "openfga/language:{{ .Tag }}-arm64"
      - "openfga/language:v{{ .Version }}-arm64"
      - "openfga/language:v{{ .Major }}-arm64"
      - "openfga/language:v{{ .Major }}.{{ .Minor }}-arm64"
      - "openfga/language:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"

    use: buildx

    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: openfga/language:latest
    image_templates:
      - openfga/language:latest-amd64
      - openfga/language:latest-arm64
  - name_template: openfga/language:v{{ .Version }}
    image_templates:
      - openfga/language:v{{ .Version }}-amd64
      - openfga/language:v{{ .Version }}-arm64
  - name_template: openfga/language:v{{ .Major }}
    image_templates:
      - openfga/language:v{{ .Major }}-amd64
      - openfga/language:v{{ .Major }}-arm64
  - name_template: openfga/language:v{{ .Major }}.{{ .Minor }}
    image_templates:
      - openfga/language:v{{ .Major }}.{{ .Minor }}-amd64
      - openfga/language:v{{ .Major }}.{{ .Minor }}-arm64
  - name_template: openfga/language:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    image_templates:
      - openfga/language:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - openfga/language:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64

release:
  github:
    owner: openfga
    name: language

sboms:
  - artifacts: archive

signs:
- cmd: cosign
  env:
  - COSIGN_EXPERIMENTAL=1
  certificate: '${artifact}.pem'
  args:
    - sign-blob
    - '--output-certificate=${certificate}'
    - '--output-signature=${signature}'
    - '${artifact}'
    - "--yes" # needed on cosign 2.0.0+
  artifacts: checksum
  output: true

docker_signs:
  - cmd: cosign
    env:
    - COSIGN_EXPERIMENTAL=1
    artifacts: manifests
    output: true
    args:
    - 'sign'
    - '${artifact}'
    - "--yes" # needed on cosign 2.0.0+

archives:
  - rlcp: true
    files:
      - assets

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
