run:
  timeout: 3m
  modules-download-mode: readonly
  allow-parallel-runners: true

skip-dirs:
  - gen

linters:
  enable-all: true
  disable:
    - godox
    - lll
    - varnamelen
    - ireturn
    - dupl #temporary
    - exhaustruct
    - gochecknoinits
    - forbidigo
    - gochecknoglobals
    # deprecated
    - testpackage
    - gci
linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/oklog/ulid/v2
          - github.com/antlr4-go/antlr/v4
          - github.com/hashicorp/go-multierror
          - github.com/openfga/api
          - google.golang.org/protobuf
          - github.com/openfga/language/pkg/go
          - gopkg.in/yaml.v3
      test:
        files:
          - "$test"
        allow:
          - $gostd
          - github.com/google/go-cmp/cmp
          - github.com/stretchr/testify
          - github.com/openfga/api
          - gopkg.in/yaml.v3
          - github.com/openfga/language/pkg/go

  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
        yaml: snake

  funlen:
    lines: 120
    statements: 80

  wrapcheck:
    ignorePackageGlobs:
      - github.com/openfga/language/pkg/go/*

  goimports:
    local-prefixes: "github.com/openfga/language/pkg/go"

issues:
  exclude-use-default: true
  exclude-rules:
    - path: _test.go
      linters:
        - funlen
