name: Test (C#)

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    name: Lint C#
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'
          cache: true
          cache-dependency-path: |
            ./pkg/csharp/src/OpenFga.Language/OpenFga.Language.csproj
            ./pkg/csharp/test/OpenFga.Language.Tests/OpenFga.Language.Tests.csproj

      - name: Lint C# source
        run: make lint-csharp

  check-gen:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Generate Antlr code and validate up to date
        run: |
            make antlr-gen-csharp
            git diff --text --exit-code ./pkg/csharp/src/OpenFga.Language/gen

  test:
    name: Test C#
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ["8.0.x", "9.0.x"]

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          cache: true
          cache-dependency-path: |
            ./pkg/csharp/src/OpenFga.Language/OpenFga.Language.csproj
            ./pkg/csharp/test/OpenFga.Language.Tests/OpenFga.Language.Tests.csproj

      - name: Test and Build with .NET
        run: make test-csharp
