name: Test (Go)
permissions:
  contents: read

permissions:
  contents: read

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ">=1.25.0"
          cache-dependency-path: "./pkg/go/go.sum"
          check-latest: true

      - name: Audit dependencies
        run: make audit-go

      - name: Lint
        run: make lint-go

  check-gen:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Generate Antlr code and validate up to date
        run: |
            make antlr-gen-go
            git diff --text --exit-code ./pkg/go/gen

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.25", "1.26"]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: "./pkg/go/go.sum"
          check-latest: true

      - name: Build
        run: make test-go
